import type { SessionScript } from '../engine/types'

const SID = 'finetune'
const h = (hours: number, mins = 0, secs = 0) =>
  ((hours * 3600 + mins * 60 + secs) * 1000)

export const finetuneScript: SessionScript = {
  meta: {
    id: SID,
    agentName: 'Cassini',
    taskTitle: 'Fine-tune the support model and evaluate',
    backend: 'gpu cluster / reserved',
    triage: 'idle',
    costUsd: 0,
  },
  events: [
    {
      id: 'f-triage',
      type: 'triage.updated',
      t: h(0, 0, 1),
      sessionId: SID,
      triage: 'running',
    },
    {
      id: 'f-thought-1',
      type: 'thought',
      t: h(0, 0, 3),
      sessionId: SID,
      text: 'Fine-tune support-8b on the curated ticket corpus, then run the held-out eval suite. This will take hours - I will checkpoint and notify on material outcomes.',
    },
    {
      id: 'f-plan',
      type: 'plan.created',
      t: h(0, 0, 6),
      sessionId: SID,
      rationale: 'Long-running training job with cost gate and delayed eval.',
      steps: [
        { id: 'f1', label: 'Estimate cost and request approval', status: 'pending' },
        { id: 'f2', label: 'Prepare dataset and launch training', status: 'pending' },
        { id: 'f3', label: 'Monitor checkpoints', status: 'pending' },
        { id: 'f4', label: 'Run held-out evaluation', status: 'pending' },
        { id: 'f5', label: 'Publish report', status: 'pending' },
      ],
    },
    {
      id: 'f-step1',
      type: 'step.started',
      t: h(0, 0, 8),
      sessionId: SID,
      stepId: 'f1',
    },
    {
      id: 'f-tool-est',
      type: 'tool.call.started',
      t: h(0, 0, 10),
      sessionId: SID,
      toolCallId: 'ft-est',
      name: 'train.estimate',
      intent: 'Estimate GPU hours and dollar cost for support-8b SFT',
      invocation: 'train.estimate(model="support-8b", steps=12000, gpus=4)',
      risk: 'low',
      stepId: 'f1',
    },
    {
      id: 'f-tool-est-out',
      type: 'tool.output',
      t: h(0, 0, 16),
      sessionId: SID,
      toolCallId: 'ft-est',
      chunk: 'Estimated wall time 4h 40m · 18.6 GPU-hours · $74.40 at current rate\n',
    },
    {
      id: 'f-tool-est-done',
      type: 'tool.call.completed',
      t: h(0, 0, 18),
      sessionId: SID,
      toolCallId: 'ft-est',
      resultChip: '$74.40 est.',
    },
    {
      id: 'f-approval',
      type: 'approval.requested',
      t: h(0, 0, 22),
      sessionId: SID,
      approval: {
        id: 'f-ap-train',
        title: 'Authorize fine-tune run',
        summary:
          'Launch support-8b SFT on 4×A100 for ~4h 40m. Estimated compute cost $74.40. Dataset: tickets-curated-v3 (184k examples).',
        evidence: [
          'Estimate from train.estimate · 18.6 GPU-hours',
          'Dataset checksum verified',
          'Eval suite support-heldout-v2 staged',
        ],
        costUsd: 74.4,
        risk: 'money',
        stepId: 'f1',
      },
    },
    {
      id: 'f-approval-scripted',
      type: 'approval.resolved',
      t: h(0, 1, 0),
      sessionId: SID,
      approvalId: 'f-ap-train',
      decision: 'approved',
    },
    {
      id: 'f-step1-done',
      type: 'step.completed',
      t: h(0, 1, 5),
      sessionId: SID,
      stepId: 'f1',
    },
    {
      id: 'f-step2',
      type: 'step.started',
      t: h(0, 1, 8),
      sessionId: SID,
      stepId: 'f2',
    },
    {
      id: 'f-tool-launch',
      type: 'tool.call.started',
      t: h(0, 1, 10),
      sessionId: SID,
      toolCallId: 'ft-launch',
      name: 'train.launch',
      intent: 'Start SFT job on reserved cluster',
      invocation: 'train.launch(job="support-8b-sft-041", gpus=4, steps=12000)',
      risk: 'medium',
      stepId: 'f2',
    },
    {
      id: 'f-tool-launch-out',
      type: 'tool.output',
      t: h(0, 1, 20),
      sessionId: SID,
      toolCallId: 'ft-launch',
      chunk: 'Job support-8b-sft-041 queued → running on node-14\n',
    },
    {
      id: 'f-tool-launch-done',
      type: 'tool.call.completed',
      t: h(0, 1, 22),
      sessionId: SID,
      toolCallId: 'ft-launch',
      resultChip: 'running',
    },
    {
      id: 'f-step2-done',
      type: 'step.completed',
      t: h(0, 1, 25),
      sessionId: SID,
      stepId: 'f2',
    },
    {
      id: 'f-step3',
      type: 'step.started',
      t: h(0, 1, 28),
      sessionId: SID,
      stepId: 'f3',
    },
    {
      id: 'f-notify-cp1',
      type: 'notification',
      t: h(1, 30, 0),
      sessionId: SID,
      title: 'Checkpoint 4k',
      body: 'Loss 1.42 · learning rate on schedule · no NaNs',
    },
    {
      id: 'f-cost-1',
      type: 'cost.updated',
      t: h(1, 30, 0),
      sessionId: SID,
      costUsd: 24.1,
    },
    {
      id: 'f-thought-2',
      type: 'thought',
      t: h(2, 45, 0),
      sessionId: SID,
      text: 'Mid-run looking healthy. Loss curve is smooth. Will hold the final checkpoint for eval rather than early-stopping - we are still within budget.',
    },
    {
      id: 'f-notify-cp2',
      type: 'notification',
      t: h(3, 10, 0),
      sessionId: SID,
      title: 'Checkpoint 8k',
      body: 'Loss 1.18 · GPU util 97% · ETA 1h 20m',
    },
    {
      id: 'f-cost-2',
      type: 'cost.updated',
      t: h(3, 10, 0),
      sessionId: SID,
      costUsd: 48.6,
    },
    {
      id: 'f-notify-done-train',
      type: 'notification',
      t: h(4, 42, 0),
      sessionId: SID,
      title: 'Training complete',
      body: 'Final loss 1.05 · artifact support-8b-sft-041.pt written',
      urgency: 'high',
    },
    {
      id: 'f-artifact-weights',
      type: 'artifact.created',
      t: h(4, 42, 10),
      sessionId: SID,
      artifact: {
        id: 'f-art-weights',
        title: 'support-8b-sft-041.pt',
        kind: 'model',
        stepId: 'f3',
        preview: '8B params · SFT · final loss 1.05 · 18.4 GPU-hours',
      },
    },
    {
      id: 'f-step3-done',
      type: 'step.completed',
      t: h(4, 42, 15),
      sessionId: SID,
      stepId: 'f3',
    },
    {
      id: 'f-step4',
      type: 'step.started',
      t: h(4, 42, 20),
      sessionId: SID,
      stepId: 'f4',
    },
    {
      id: 'f-tool-eval',
      type: 'tool.call.started',
      t: h(4, 42, 30),
      sessionId: SID,
      toolCallId: 'ft-eval',
      name: 'eval.run',
      intent: 'Run support-heldout-v2 against new checkpoint',
      invocation: 'eval.run(suite="support-heldout-v2", model="support-8b-sft-041")',
      risk: 'low',
      stepId: 'f4',
    },
    {
      id: 'f-tool-eval-out',
      type: 'tool.output',
      t: h(5, 5, 0),
      sessionId: SID,
      toolCallId: 'ft-eval',
      chunk:
        'exact_match 0.71 (+0.06)\nhelpfulness 4.2/5 (+0.3)\nrefusal_quality 0.94 (−0.01)\n',
    },
    {
      id: 'f-tool-eval-done',
      type: 'tool.call.completed',
      t: h(5, 5, 10),
      sessionId: SID,
      toolCallId: 'ft-eval',
      resultChip: '+0.06 EM',
    },
    {
      id: 'f-step4-done',
      type: 'step.completed',
      t: h(5, 5, 15),
      sessionId: SID,
      stepId: 'f4',
    },
    {
      id: 'f-step5',
      type: 'step.started',
      t: h(5, 5, 20),
      sessionId: SID,
      stepId: 'f5',
    },
    {
      id: 'f-artifact-report',
      type: 'artifact.created',
      t: h(5, 8, 0),
      sessionId: SID,
      artifact: {
        id: 'f-art-report',
        title: 'Fine-tune evaluation report',
        kind: 'document',
        stepId: 'f5',
        toolCallId: 'ft-eval',
        preview:
          'support-8b-sft-041 beats baseline on EM and helpfulness. Slight refusal regression (−0.01) - within noise. Recommend staged canary.',
      },
    },
    {
      id: 'f-memory',
      type: 'memory.noted',
      t: h(5, 8, 20),
      sessionId: SID,
      memory: {
        id: 'f-mem',
        text: 'For support fine-tunes, you prefer staged canaries over immediate full rollout.',
      },
    },
    {
      id: 'f-skill',
      type: 'skill.proposed',
      t: h(5, 9, 0),
      sessionId: SID,
      skill: {
        id: 'f-sk',
        name: 'Support Model Fine-Tune',
        description:
          'Estimate → cost gate → launch SFT → checkpoint monitor → held-out eval → report with canary recommendation.',
      },
    },
    {
      id: 'f-cost-final',
      type: 'cost.updated',
      t: h(5, 9, 0),
      sessionId: SID,
      costUsd: 76.2,
    },
    {
      id: 'f-step5-done',
      type: 'step.completed',
      t: h(5, 9, 10),
      sessionId: SID,
      stepId: 'f5',
    },
    {
      id: 'f-done',
      type: 'triage.updated',
      t: h(5, 9, 15),
      sessionId: SID,
      triage: 'done',
    },
  ],
}
