import type { SessionScript } from '../engine/types'

const SID = 'nightly-build'
const m = (mins: number, secs = 0) => (mins * 60 + secs) * 1000

export const nightlyBuildScript: SessionScript = {
  meta: {
    id: SID,
    agentName: 'Halley',
    taskTitle: 'Fix the failing nightly build',
    backend: 'docker / local',
    triage: 'running',
    costUsd: 0,
  },
  events: [
    {
      id: 'n-triage',
      type: 'triage.updated',
      t: m(0, 1),
      sessionId: SID,
      triage: 'running',
    },
    {
      id: 'n-thought-1',
      type: 'thought',
      t: m(0, 2),
      sessionId: SID,
      text: 'Nightly pipeline failed on main at 02:14 UTC. Starting with the failing job log before touching any code.',
    },
    {
      id: 'n-plan',
      type: 'plan.created',
      t: m(0, 4),
      sessionId: SID,
      rationale: 'Diagnose, patch, verify, then gate the push.',
      steps: [
        { id: 'n1', label: 'Pull failing job logs', status: 'pending' },
        { id: 'n2', label: 'Locate regression in recent commits', status: 'pending' },
        { id: 'n3', label: 'Draft minimal patch', status: 'pending' },
        { id: 'n4', label: 'Run targeted tests', status: 'pending' },
        { id: 'n5', label: 'Push fix (approval required)', status: 'pending' },
      ],
    },
    {
      id: 'n-step1',
      type: 'step.started',
      t: m(0, 5),
      sessionId: SID,
      stepId: 'n1',
    },
    {
      id: 'n-tool-logs',
      type: 'tool.call.started',
      t: m(0, 6),
      sessionId: SID,
      toolCallId: 'nt-logs',
      name: 'ci.fetch_logs',
      intent: 'Retrieve nightly-build job log from last failure',
      invocation: 'ci.fetch_logs(pipeline="nightly", job="typecheck")',
      risk: 'low',
      stepId: 'n1',
    },
    {
      id: 'n-tool-logs-out',
      type: 'tool.output',
      t: m(0, 10),
      sessionId: SID,
      toolCallId: 'nt-logs',
      chunk:
        'error TS2345: Argument of type \'string | undefined\' is not assignable…\n  at src/gateway/sessions.ts:218:14\n',
    },
    {
      id: 'n-tool-logs-done',
      type: 'tool.call.completed',
      t: m(0, 12),
      sessionId: SID,
      toolCallId: 'nt-logs',
      resultChip: 'TS2345 @ sessions.ts:218',
    },
    {
      id: 'n-step1-done',
      type: 'step.completed',
      t: m(0, 13),
      sessionId: SID,
      stepId: 'n1',
    },
    {
      id: 'n-step2',
      type: 'step.started',
      t: m(0, 14),
      sessionId: SID,
      stepId: 'n2',
    },
    {
      id: 'n-tool-blame',
      type: 'tool.call.started',
      t: m(0, 15),
      sessionId: SID,
      toolCallId: 'nt-blame',
      name: 'repo.search',
      intent: 'Find recent changes to sessions.ts narrowing',
      invocation: 'repo.search(path="src/gateway/sessions.ts", query="sessionId", since="24h")',
      risk: 'low',
      stepId: 'n2',
    },
    {
      id: 'n-tool-blame-out',
      type: 'tool.output',
      t: m(0, 20),
      sessionId: SID,
      toolCallId: 'nt-blame',
      chunk: 'commit a3f91c2 · "relax session lookup" · removed non-null assertion on sessionId\n',
    },
    {
      id: 'n-tool-blame-done',
      type: 'tool.call.completed',
      t: m(0, 22),
      sessionId: SID,
      toolCallId: 'nt-blame',
      resultChip: 'a3f91c2',
    },
    {
      id: 'n-cost-1',
      type: 'cost.updated',
      t: m(0, 22),
      sessionId: SID,
      costUsd: 0.08,
    },
    {
      id: 'n-step2-done',
      type: 'step.completed',
      t: m(0, 23),
      sessionId: SID,
      stepId: 'n2',
    },
    {
      id: 'n-step3',
      type: 'step.started',
      t: m(0, 24),
      sessionId: SID,
      stepId: 'n3',
    },
    {
      id: 'n-thought-2',
      type: 'thought',
      t: m(0, 26),
      sessionId: SID,
      text: 'Minimal fix: early-return when sessionId is undefined, rather than restoring the assertion. Keeps the intent of a3f91c2 without breaking the typecheck.',
    },
    {
      id: 'n-artifact-patch',
      type: 'artifact.created',
      t: m(0, 32),
      sessionId: SID,
      artifact: {
        id: 'n-art-patch',
        title: 'sessions.ts early-return patch',
        kind: 'diff',
        stepId: 'n3',
        preview:
          '+ if (!sessionId) return null\n  const session = store.get(sessionId)\n- const session = store.get(sessionId!)',
      },
    },
    {
      id: 'n-step3-done',
      type: 'step.completed',
      t: m(0, 34),
      sessionId: SID,
      stepId: 'n3',
    },
    {
      id: 'n-step4',
      type: 'step.started',
      t: m(0, 35),
      sessionId: SID,
      stepId: 'n4',
    },
    {
      id: 'n-tool-test',
      type: 'tool.call.started',
      t: m(0, 36),
      sessionId: SID,
      toolCallId: 'nt-test',
      name: 'shell.run',
      intent: 'Run typecheck and gateway unit tests',
      invocation: 'shell.run("pnpm typecheck && pnpm test gateway")',
      risk: 'medium',
      stepId: 'n4',
    },
    {
      id: 'n-tool-test-out',
      type: 'tool.output',
      t: m(0, 48),
      sessionId: SID,
      toolCallId: 'nt-test',
      chunk: 'typecheck ok\ngateway · 42 passed · 0 failed\n',
    },
    {
      id: 'n-tool-test-done',
      type: 'tool.call.completed',
      t: m(0, 50),
      sessionId: SID,
      toolCallId: 'nt-test',
      resultChip: '42 passed',
    },
    {
      id: 'n-step4-done',
      type: 'step.completed',
      t: m(0, 51),
      sessionId: SID,
      stepId: 'n4',
    },
    {
      id: 'n-step5',
      type: 'step.started',
      t: m(0, 52),
      sessionId: SID,
      stepId: 'n5',
    },
    {
      id: 'n-approval',
      type: 'approval.requested',
      t: m(0, 54),
      sessionId: SID,
      approval: {
        id: 'n-ap-push',
        title: 'Push fix to main',
        summary:
          'Commit the early-return patch and push to main to unblock nightly. Diff is four lines in src/gateway/sessions.ts.',
        evidence: [
          'typecheck clean',
          'gateway unit tests 42/42',
          'Root cause: a3f91c2 removed assertion without guard',
        ],
        risk: 'high',
        stepId: 'n5',
      },
    },
    {
      id: 'n-approval-scripted',
      type: 'approval.resolved',
      t: m(1, 0),
      sessionId: SID,
      approvalId: 'n-ap-push',
      decision: 'approved',
    },
    {
      id: 'n-tool-push',
      type: 'tool.call.started',
      t: m(1, 2),
      sessionId: SID,
      toolCallId: 'nt-push',
      name: 'repo.push',
      intent: 'Commit and push the fix',
      invocation: 'repo.push(branch="main", message="fix(gateway): guard undefined sessionId")',
      risk: 'destructive',
      stepId: 'n5',
    },
    {
      id: 'n-tool-push-out',
      type: 'tool.output',
      t: m(1, 8),
      sessionId: SID,
      toolCallId: 'nt-push',
      chunk: 'pushed c81e2aa → origin/main\n',
    },
    {
      id: 'n-tool-push-done',
      type: 'tool.call.completed',
      t: m(1, 10),
      sessionId: SID,
      toolCallId: 'nt-push',
      resultChip: 'c81e2aa',
    },
    {
      id: 'n-memory',
      type: 'memory.noted',
      t: m(1, 12),
      sessionId: SID,
      memory: {
        id: 'n-mem',
        text: 'Nightly typecheck failures in gateway usually trace to optional narrowing - check assertions before broad refactors.',
      },
    },
    {
      id: 'n-cost-final',
      type: 'cost.updated',
      t: m(1, 12),
      sessionId: SID,
      costUsd: 0.21,
    },
    {
      id: 'n-step5-done',
      type: 'step.completed',
      t: m(1, 14),
      sessionId: SID,
      stepId: 'n5',
    },
    {
      id: 'n-done',
      type: 'triage.updated',
      t: m(1, 15),
      sessionId: SID,
      triage: 'done',
    },
  ],
}
