import type { SessionScript } from '../engine/types'

const SID = 'offsite'
const h = (hours: number, mins = 0, secs = 0) =>
  ((hours * 3600 + mins * 60 + secs) * 1000)

export const offsiteScript: SessionScript = {
  meta: {
    id: SID,
    agentName: 'Kepler',
    taskTitle: 'Plan and book the team research offsite',
    backend: 'serverless / hibernating',
    triage: 'idle',
    costUsd: 0,
  },
  events: [
    {
      id: 'o-triage',
      type: 'triage.updated',
      t: h(0, 0, 1),
      sessionId: SID,
      triage: 'running',
    },
    {
      id: 'o-thought-1',
      type: 'thought',
      t: h(0, 0, 2),
      sessionId: SID,
      text: 'Team of six, three-day research offsite within six weeks. Preference for somewhere quiet with strong wifi and a whiteboard wall. Budget ceiling roughly four thousand dollars all-in.',
    },
    {
      id: 'o-plan',
      type: 'plan.created',
      t: h(0, 0, 5),
      sessionId: SID,
      rationale: 'Plan established for offsite research and booking.',
      steps: [
        { id: 's1', label: 'Clarify constraints with operator', status: 'pending' },
        { id: 's2', label: 'Shortlist destinations and venues', status: 'pending' },
        { id: 's3', label: 'Compare flights and lodging', status: 'pending' },
        { id: 's4', label: 'Draft itinerary and budget', status: 'pending' },
        { id: 's5', label: 'Secure bookings (approval required)', status: 'pending' },
        { id: 's6', label: 'Publish packet and capture learnings', status: 'pending' },
      ],
    },
    {
      id: 'o-step1',
      type: 'step.started',
      t: h(0, 0, 6),
      sessionId: SID,
      stepId: 's1',
    },
    {
      id: 'o-thought-2',
      type: 'thought',
      t: h(0, 0, 8),
      sessionId: SID,
      text: 'I will assume departure from SFO, midweek stay to keep fares sane, and a venue with a private work room. Flagging anything over budget for approval rather than auto-booking.',
    },
    {
      id: 'o-notify-clarify',
      type: 'notification',
      t: h(0, 0, 10),
      sessionId: SID,
      title: 'Assumptions locked',
      body: 'SFO origin · midweek · private work room · $4,000 ceiling',
    },
    {
      id: 'o-step1-done',
      type: 'step.completed',
      t: h(0, 0, 12),
      sessionId: SID,
      stepId: 's1',
    },
    {
      id: 'o-step2',
      type: 'step.started',
      t: h(0, 0, 14),
      sessionId: SID,
      stepId: 's2',
    },
    {
      id: 'o-tool-search',
      type: 'tool.call.started',
      t: h(0, 0, 16),
      sessionId: SID,
      toolCallId: 'tc-search-1',
      name: 'web.search',
      intent: 'Find quiet research retreat venues within 2h of a major airport',
      invocation: 'web.search("research retreat venue wifi whiteboard California Oregon Washington spring")',
      risk: 'low',
      stepId: 's2',
    },
    {
      id: 'o-tool-search-out1',
      type: 'tool.output',
      t: h(0, 0, 18),
      sessionId: SID,
      toolCallId: 'tc-search-1',
      chunk: '12 results · filtering for private rooms + fiber…\n',
    },
    {
      id: 'o-tool-search-out2',
      type: 'tool.output',
      t: h(0, 0, 22),
      sessionId: SID,
      toolCallId: 'tc-search-1',
      chunk:
        '1. Sea Ranch Lodge - Mendocino coast\n2. Packwood Cabin Campus - Mt. Rainier corridor\n3. Point Reyes Field Station - Marin\n',
    },
    {
      id: 'o-tool-search-done',
      type: 'tool.call.completed',
      t: h(0, 0, 24),
      sessionId: SID,
      toolCallId: 'tc-search-1',
      resultChip: '3 shortlisted',
    },
    {
      id: 'o-cost-1',
      type: 'cost.updated',
      t: h(0, 0, 24),
      sessionId: SID,
      costUsd: 0.12,
    },
    {
      id: 'o-thought-3',
      type: 'thought',
      t: h(0, 0, 28),
      sessionId: SID,
      text: 'Sea Ranch is beautiful but wifi reviews are mixed. Packwood has a dedicated work barn and reliable fiber. Point Reyes is closest - under two hours by car, no flights needed.',
    },
    {
      id: 'o-step2-done',
      type: 'step.completed',
      t: h(0, 0, 32),
      sessionId: SID,
      stepId: 's2',
    },
    {
      id: 'o-step3',
      type: 'step.started',
      t: h(0, 0, 34),
      sessionId: SID,
      stepId: 's3',
    },
    {
      id: 'o-tool-flights',
      type: 'tool.call.started',
      t: h(0, 0, 36),
      sessionId: SID,
      toolCallId: 'tc-flights',
      name: 'travel.search_flights',
      intent: 'Price SFO→SEA midweek for Packwood option',
      invocation: 'travel.search_flights(origin="SFO", dest="SEA", date="2026-09-15", pax=6)',
      risk: 'low',
      stepId: 's3',
    },
    {
      id: 'o-tool-flights-out',
      type: 'tool.output',
      t: h(0, 0, 42),
      sessionId: SID,
      toolCallId: 'tc-flights',
      chunk: 'Alaska AS312 · 07:05 depart · $148/seat · 6 seats available\nUnited UA758 · 09:40 · $189/seat · 4 seats\n',
    },
    {
      id: 'o-tool-flights-done',
      type: 'tool.call.completed',
      t: h(0, 0, 44),
      sessionId: SID,
      toolCallId: 'tc-flights',
      resultChip: '$888 AS312',
    },
    {
      id: 'o-tool-lodge',
      type: 'tool.call.started',
      t: h(0, 0, 48),
      sessionId: SID,
      toolCallId: 'tc-lodge',
      name: 'travel.search_lodging',
      intent: 'Check Packwood Cabin Campus availability',
      invocation: 'travel.search_lodging(venue="Packwood Cabin Campus", checkin="2026-09-15", nights=3)',
      risk: 'low',
      stepId: 's3',
    },
    {
      id: 'o-tool-lodge-out',
      type: 'tool.output',
      t: h(0, 0, 55),
      sessionId: SID,
      toolCallId: 'tc-lodge',
      chunk: 'Work Barn + 3 cabins · $1,640 total · fiber confirmed · whiteboard wall yes\n',
    },
    {
      id: 'o-tool-lodge-done',
      type: 'tool.call.completed',
      t: h(0, 0, 58),
      sessionId: SID,
      toolCallId: 'tc-lodge',
      resultChip: '$1,640 available',
    },
    {
      id: 'o-cost-2',
      type: 'cost.updated',
      t: h(0, 0, 58),
      sessionId: SID,
      costUsd: 0.31,
    },
    // Time jump - flights sell out later
    {
      id: 'o-thought-4',
      type: 'thought',
      t: h(1, 12, 0),
      sessionId: SID,
      text: 'Re-checking inventory before drafting the packet. Morning Alaska block may have thinned overnight.',
    },
    {
      id: 'o-tool-recheck',
      type: 'tool.call.started',
      t: h(1, 12, 10),
      sessionId: SID,
      toolCallId: 'tc-recheck',
      name: 'travel.search_flights',
      intent: 'Revalidate AS312 seat inventory',
      invocation: 'travel.search_flights(origin="SFO", dest="SEA", date="2026-09-15", pax=6, flight="AS312")',
      risk: 'low',
      stepId: 's3',
    },
    {
      id: 'o-tool-recheck-out',
      type: 'tool.output',
      t: h(1, 12, 18),
      sessionId: SID,
      toolCallId: 'tc-recheck',
      chunk: 'AS312 · 2 seats remaining - cannot fulfill party of 6\nNext viable: AS480 · 14:20 · $162/seat · 6 seats\n',
    },
    {
      id: 'o-tool-recheck-done',
      type: 'tool.call.completed',
      t: h(1, 12, 20),
      sessionId: SID,
      toolCallId: 'tc-recheck',
      resultChip: 'sold out → AS480',
    },
    {
      id: 'o-plan-revise',
      type: 'plan.revised',
      t: h(1, 12, 25),
      sessionId: SID,
      reason: 'Morning flight AS312 sold down to 2 seats. Switching to afternoon AS480 and shifting cabin check-in by four hours.',
      diff: {
        added: ['Shift cabin check-in to 18:00', 'Add airport shuttle buffer'],
        removed: ['07:05 AS312 block'],
        changed: ['Compare flights and lodging → book AS480 14:20'],
      },
      steps: [
        { id: 's1', label: 'Clarify constraints with operator', status: 'done' },
        { id: 's2', label: 'Shortlist destinations and venues', status: 'done' },
        { id: 's3', label: 'Compare flights and lodging', status: 'active' },
        { id: 's4', label: 'Draft itinerary and budget', status: 'pending' },
        { id: 's5', label: 'Secure bookings (approval required)', status: 'pending' },
        { id: 's6', label: 'Publish packet and capture learnings', status: 'pending' },
        { id: 's3b', label: 'Arrange airport shuttle buffer', status: 'pending' },
      ],
    },
    {
      id: 'o-step3-done',
      type: 'step.completed',
      t: h(1, 12, 30),
      sessionId: SID,
      stepId: 's3',
    },
    {
      id: 'o-step4',
      type: 'step.started',
      t: h(1, 12, 32),
      sessionId: SID,
      stepId: 's4',
    },
    {
      id: 'o-thought-5',
      type: 'thought',
      t: h(1, 12, 40),
      sessionId: SID,
      text: 'Building the itinerary packet: flights, lodging, shuttle, daily agenda skeleton, and a cost rollup under the four-thousand ceiling.',
    },
    {
      id: 'o-artifact-itin',
      type: 'artifact.created',
      t: h(1, 15, 0),
      sessionId: SID,
      artifact: {
        id: 'art-itin',
        title: 'Offsite itinerary - Packwood · Sep 15-18',
        kind: 'document',
        stepId: 's4',
        toolCallId: 'tc-recheck',
        preview:
          'Day 0 · AS480 SFO→SEA 14:20 · shuttle to Packwood\nDay 1-2 · Work Barn sessions · evening walks\nDay 3 · depart SEA 16:10',
      },
    },
    {
      id: 'o-artifact-budget',
      type: 'artifact.created',
      t: h(1, 15, 20),
      sessionId: SID,
      artifact: {
        id: 'art-budget',
        title: 'Budget rollup',
        kind: 'spreadsheet',
        stepId: 's4',
        preview: 'Flights $972 · Lodging $1,640 · Shuttle $180 · Meals est. $720 · Buffer $200 · Total $3,712',
      },
    },
    {
      id: 'o-cost-3',
      type: 'cost.updated',
      t: h(1, 15, 20),
      sessionId: SID,
      costUsd: 0.54,
    },
    {
      id: 'o-step4-done',
      type: 'step.completed',
      t: h(1, 15, 30),
      sessionId: SID,
      stepId: 's4',
    },
    {
      id: 'o-step5',
      type: 'step.started',
      t: h(1, 15, 35),
      sessionId: SID,
      stepId: 's5',
    },
    {
      id: 'o-approval',
      type: 'approval.requested',
      t: h(1, 15, 40),
      sessionId: SID,
      approval: {
        id: 'ap-book',
        title: 'Authorize flight + lodging purchase',
        summary:
          'Charge $2,612 to the research travel card for AS480 (6 seats) and Packwood Cabin Campus (3 nights). Remains $1,100 under the $4,000 ceiling after estimated meals and shuttle.',
        evidence: [
          'AS480 inventory confirmed · 6 seats at $162',
          'Packwood Work Barn + cabins held for 45 minutes',
          'Budget rollup total projected $3,712',
          'Morning AS312 no longer viable (2 seats)',
        ],
        costUsd: 2612,
        risk: 'money',
        stepId: 's5',
        expiresAt: h(1, 16, 25),
      },
    },
    // Scripted resolution is skipped by the player - user must approve
    {
      id: 'o-approval-scripted',
      type: 'approval.resolved',
      t: h(1, 16, 0),
      sessionId: SID,
      approvalId: 'ap-book',
      decision: 'approved',
    },
    {
      id: 'o-tool-book',
      type: 'tool.call.started',
      t: h(1, 16, 5),
      sessionId: SID,
      toolCallId: 'tc-book',
      name: 'travel.purchase',
      intent: 'Execute approved flight and lodging booking',
      invocation: 'travel.purchase(flights="AS480×6", lodging="Packwood Cabin Campus", amount=2612)',
      risk: 'destructive',
      stepId: 's5',
    },
    {
      id: 'o-tool-book-out',
      type: 'tool.output',
      t: h(1, 16, 15),
      sessionId: SID,
      toolCallId: 'tc-book',
      chunk: 'Payment authorized · PNR KPL482 · lodging conf PCC-91833\n',
    },
    {
      id: 'o-tool-book-done',
      type: 'tool.call.completed',
      t: h(1, 16, 18),
      sessionId: SID,
      toolCallId: 'tc-book',
      resultChip: 'booked',
    },
    {
      id: 'o-artifact-conf',
      type: 'artifact.created',
      t: h(1, 16, 22),
      sessionId: SID,
      artifact: {
        id: 'art-conf',
        title: 'Booking confirmations',
        kind: 'receipt',
        stepId: 's5',
        toolCallId: 'tc-book',
        preview: 'PNR KPL482 · PCC-91833 · charged $2,612.00',
      },
    },
    {
      id: 'o-step5-done',
      type: 'step.completed',
      t: h(1, 16, 25),
      sessionId: SID,
      stepId: 's5',
    },
    {
      id: 'o-step3b',
      type: 'step.started',
      t: h(1, 16, 28),
      sessionId: SID,
      stepId: 's3b',
    },
    {
      id: 'o-tool-shuttle',
      type: 'tool.call.started',
      t: h(1, 16, 30),
      sessionId: SID,
      toolCallId: 'tc-shuttle',
      name: 'travel.book_transfer',
      intent: 'Reserve SEA→Packwood van for six',
      invocation: 'travel.book_transfer(from="SEA", to="Packwood", pax=6, time="15:45")',
      risk: 'medium',
      stepId: 's3b',
    },
    {
      id: 'o-tool-shuttle-out',
      type: 'tool.output',
      t: h(1, 16, 40),
      sessionId: SID,
      toolCallId: 'tc-shuttle',
      chunk: 'Cascade Van Co · $180 · confirmation CV-4401\n',
    },
    {
      id: 'o-tool-shuttle-done',
      type: 'tool.call.completed',
      t: h(1, 16, 42),
      sessionId: SID,
      toolCallId: 'tc-shuttle',
      resultChip: '$180 reserved',
    },
    {
      id: 'o-step3b-done',
      type: 'step.completed',
      t: h(1, 16, 45),
      sessionId: SID,
      stepId: 's3b',
    },
    {
      id: 'o-step6',
      type: 'step.started',
      t: h(1, 17, 0),
      sessionId: SID,
      stepId: 's6',
    },
    {
      id: 'o-memory',
      type: 'memory.noted',
      t: h(1, 17, 10),
      sessionId: SID,
      memory: {
        id: 'mem-morning',
        text: 'You prefer morning flights when inventory allows - noted for future travel tasks.',
      },
    },
    {
      id: 'o-artifact-packet',
      type: 'artifact.created',
      t: h(1, 17, 30),
      sessionId: SID,
      artifact: {
        id: 'art-packet',
        title: 'Team offsite packet',
        kind: 'document',
        stepId: 's6',
        preview: 'Itinerary · budget · confirmations · packing note · wifi credentials request',
      },
    },
    {
      id: 'o-skill',
      type: 'skill.proposed',
      t: h(1, 18, 0),
      sessionId: SID,
      skill: {
        id: 'sk-offsite',
        name: 'Offsite Planning',
        description:
          'Reusable skill: clarify constraints → shortlist venues → price flights/lodging → draft packet → gate purchases behind approval → capture travel preferences.',
      },
    },
    {
      id: 'o-cost-final',
      type: 'cost.updated',
      t: h(1, 18, 0),
      sessionId: SID,
      costUsd: 0.89,
    },
    {
      id: 'o-step6-done',
      type: 'step.completed',
      t: h(1, 18, 10),
      sessionId: SID,
      stepId: 's6',
    },
    {
      id: 'o-notify-done',
      type: 'notification',
      t: h(1, 18, 15),
      sessionId: SID,
      title: 'Offsite secured',
      body: 'Packet published. Bookings confirmed. Skill proposal awaiting your call.',
      urgency: 'normal',
    },
    {
      id: 'o-triage-done',
      type: 'triage.updated',
      t: h(1, 18, 20),
      sessionId: SID,
      triage: 'done',
    },
  ],
}
